version: "2"
services:
  comments_app:
    container_name: app_container
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo_service
  mongo_service:
    container_name: mongo_container
    image: mongo
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"